version: "3.2"

services:

  portal:
    # image: $${DOCKER_REGISTRY:?}/polymny/server:$${GIT_TAG:latest}
    image: registry.polymny.studio/polymny/portal:${TAG}
    build:
      context: .
      target: portal
    ports:
      - 8000:80
    restart: unless-stopped

