version: "3.2"

services:

  portal:
    # image: $${DOCKER_REGISTRY:?}/polymny/server:$${GIT_TAG:latest}
    image: exln6chq.gra7.container-registry.ovh.net/polymny/portal:${TAG}
    build:
      context: .
      target: portal
    ports:
      - 80
    restart: unless-stopped

